typography_spectrum: 0.5713867356535047
color:
  brandStrength: 0.034225156996399164
  lightness: 0.9672048888169229
  saturation: 0.5100797282066196
  rhythmicContrast: 0.842632855521515
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
layout_spectrum: 0.15166862960904837
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2d6ba383-fcda-42cd-853d-3557333b3b5d.jpg
name: AllGreen Marketing Solutions Inc.
navigation:
  - name: 15% Tax on Foreign Real Estate buyers in Vancouver
    id: 53ea0000-d214-4d05-90dc-bba4e1bfdda3
    type: content
title: What is the problems you want to solve today?
description: Finding Answers
